return {
  eslint = require 'diagnosticls-nvim.linters.eslint',
  flake8 = require 'diagnosticls-nvim.linters.flake8',
  golangci_lint = require 'diagnosticls-nvim.linters.golangci_lint',
  phpcs = require 'diagnosticls-nvim.linters.phpcs',
  phpstan = require 'diagnosticls-nvim.linters.phpstan',
  psalm = require 'diagnosticls-nvim.linters.psalm',
  pylint = require 'diagnosticls-nvim.linters.pylint',
  reek = require 'diagnosticls-nvim.linters.reek',
  revive = require 'diagnosticls-nvim.linters.revive',
  rubocop = require 'diagnosticls-nvim.linters.rubocop',
  standard = require 'diagnosticls-nvim.linters.standard',
  stylelint = require 'diagnosticls-nvim.linters.stylelint',
  ts_standard = require 'diagnosticls-nvim.linters.ts_standard',
  vint = require 'diagnosticls-nvim.linters.vint',
  xo = require 'diagnosticls-nvim.linters.xo',
}
